apiVersion: v1
kind: Service
metadata:
  name: minecraft-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: minecraft-minecraft
  ports:
    - name: minecraft
      port: 25565
      targetPort: minecraft
      nodePort: 30002